main: ca.cactusmc.gui.plugin.CGUIJavaPlugin
name: CactusGUI
author: CCMW
version: 1.0
api-version: 1.13
description: GUI utility meant to bring convenience in making functional GUIs to developers.
commands:
   cgui:
      usage: /cgui